/**
 * @license
 * Copyright 2023 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

import * as Blockly from 'blockly';

const color = {
  block: '#D4816B',
  control: '#6BB2B2',
  operation: '#877BAD',
  io: '#A08A8A',
  unit: '#C7B59D',
  world: '#6B84D4',
  var: 110,
  bang: 250,
};

const radar_target = [
  ['any', 'any'],
  ['enemy', 'enemy'],
  ['ally', 'ally'],
  ['player', 'player'],
  ['attacker', 'attacker'],
  ['flying', 'flying'],
  ['boss', 'boss'],
  ['ground', 'ground'],
];
const radar_sort = [
  ['distance', 'distance'],
  ['health', 'health'],
  ['shield', 'shield'],
  ['armor', 'armor'],
  ['maxHealth', 'maxHealth'],
];

export const blocks = Blockly.common.createBlockDefinitionsFromJsonArray([
  {
    type: 'LogicLineOther',
    message0: 'Other %1%2%3%4%5%6%7%8%9%10%11%12%13%14%15',
    args0: [
      { type: 'input_value', name: 'ARG0',  check: 'Value', },
      { type: 'input_value', name: 'ARG1',  check: 'Value', },
      { type: 'input_value', name: 'ARG2',  check: 'Value', },
      { type: 'input_value', name: 'ARG3',  check: 'Value', },
      { type: 'input_value', name: 'ARG4',  check: 'Value', },
      { type: 'input_value', name: 'ARG5',  check: 'Value', },
      { type: 'input_value', name: 'ARG6',  check: 'Value', },
      { type: 'input_value', name: 'ARG7',  check: 'Value', },
      { type: 'input_value', name: 'ARG8',  check: 'Value', },
      { type: 'input_value', name: 'ARG9',  check: 'Value', },
      { type: 'input_value', name: 'ARG10', check: 'Value', },
      { type: 'input_value', name: 'ARG11', check: 'Value', },
      { type: 'input_value', name: 'ARG12', check: 'Value', },
      { type: 'input_value', name: 'ARG13', check: 'Value', },
      { type: 'input_value', name: 'ARG14', check: 'Value', },
    ],
    inputsInline: true,
    previousStatement: null,
    nextStatement: null,
    colour: color.bang,
  },
  {
    type: 'Var',
    message0: 'Var %1',
    args0: [
      {
        type: 'field_input',
        name: 'NAME',
        text: 'var',
      },
    ],
    output: ['Var', 'Value'],
    colour: color.var,
  },
  {
    type: 'String',
    message0: 'Str "%1"',
    args0: [
      {
        type: 'field_input',
        name: 'TEXT',
        text: 'foo',
      },
    ],
    output: ['Var', 'Value'],
    colour: color.var,
  },
  {
    type: 'MultilineString',
    message0: 'MlStr "%1"',
    args0: [
      {
        type: 'field_multilinetext',
        name: 'TEXT',
        text: 'foo\nbar',
      },
    ],
    output: ['Var', 'Value'],
    colour: color.var,
  },
  {
    type: 'ToValue',
    message0: 'ToValue %1',
    args0: [
      {
        type: 'input_value',
        name: 'VALUE',
        check: 'Value'
      },
    ],
    inputsInline: true,
    output: 'Value',
    colour: color.var,
  },
  {
    type: 'Block',
    message0: '{',
    args0: [],
    message1: '%1',
    args1: [
      {
        type: 'input_statement',
        name: 'LINES',
      },
    ],
    message2: '}',
    args2: [],
    previousStatement: null,
    nextStatement: null,
    colour: color.bang,
  },
  {
    type: 'Arg1Control',
    message0: '%1 %2%3',
    args0: [
      {
        type: 'field_dropdown',
        name: 'TYPE',
        options: [
          ['while', 'while'],
          ['skip', 'skip'],
          ['select', 'select'],
          ['if', 'if'],
          ['elif', 'elif'],
          ['switch', 'switch'],
        ],
      },
      {
        type: 'input_value',
        name: 'VALUE',
        check: 'Value',
      },
      {
        type: 'input_statement',
        name: 'LINES',
      },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: color.bang,
  },
  {
    type: 'LogicRead',
    message0: 'Read %1 %2 %3',
    args0: [
      {
        type: 'input_value',
        name: 'RESULT',
        check: 'Value',
      },
      {
        type: 'input_value',
        name: 'MEMORY',
        check: 'Value',
      },
      {
        type: 'input_value',
        name: 'ADDRESS',
        check: 'Value',
      },
    ],
    inputsInline: true,
    previousStatement: null,
    nextStatement: null,
    colour: color.io,
  },
  {
    type: 'LogicWrite',
    message0: 'Write %1 %2 %3',
    args0: [
      {
        type: 'input_value',
        name: 'VALUE',
        check: 'Value',
      },
      {
        type: 'input_value',
        name: 'MEMORY',
        check: 'Value',
      },
      {
        type: 'input_value',
        name: 'ADDRESS',
        check: 'Value',
      },
    ],
    inputsInline: true,
    previousStatement: null,
    nextStatement: null,
    colour: color.io,
  },
  {
    type: 'LogicDraw',
    message0: 'Draw %1%2%3%4%5%6%7%8%9%10%11%12%13',
    args0: [
      {
        type: 'field_dropdown',
        name: 'TYPE',
        options: [
          ['clear', 'clear'],
          ['color', 'color'],
          ['col', 'col'],
          ['stroke', 'stroke'],
          ['line', 'line'],
          ['rect', 'rect'],
          ['lineRect', 'lineRect'],
          ['poly', 'poly'],
          ['linePoly', 'linePoly'],
          ['triangle', 'triangle'],
          ['image', 'image'],
        ],
      },
      {
        type: 'field_label_serializable',
        name: 'ARG1S',
      },
      {
        type: 'input_value',
        name: 'ARG1',
        check: 'Value',
      },
      {
        type: 'field_label_serializable',
        name: 'ARG2S',
      },
      {
        type: 'input_value',
        name: 'ARG2',
        check: 'Value',
      },
      {
        type: 'field_label_serializable',
        name: 'ARG3S',
      },
      {
        type: 'input_value',
        name: 'ARG3',
        check: 'Value',
      },
      {
        type: 'field_label_serializable',
        name: 'ARG4S',
      },
      {
        type: 'input_value',
        name: 'ARG4',
        check: 'Value',
      },
      {
        type: 'field_label_serializable',
        name: 'ARG5S',
      },
      {
        type: 'input_value',
        name: 'ARG5',
        check: 'Value',
      },
      {
        type: 'field_label_serializable',
        name: 'ARG6S',
      },
      {
        type: 'input_value',
        name: 'ARG6',
        check: 'Value',
      },
    ],
    inputsInline: true,
    previousStatement: null,
    nextStatement: null,
    colour: color.io,
  },
  {
    type: 'LogicPrint',
    message0: 'Print %1',
    args0: [
      {
        type: 'input_value',
        name: 'VALUE',
        check: 'Value',
      },
    ],
    inputsInline: true,
    previousStatement: null,
    nextStatement: null,
    colour: color.io,
  },
  { type: 'LogicDrawFlush',
    message0: 'DrawFlush %1',
    args0: [
      {
        type: 'input_value',
        name: 'VALUE',
        check: 'Value',
      },
    ],
    inputsInline: true,
    previousStatement: null,
    nextStatement: null,
    colour: color.block,
  },
  {
    type: 'LogicPrintFlush',
    message0: 'PrintFlush %1',
    args0: [
      {
        type: 'input_value',
        name: 'VALUE',
        check: 'Value',
      },
    ],
    inputsInline: true,
    previousStatement: null,
    nextStatement: null,
    colour: color.block,
  },
  {
    type: 'LogicGetLink',
    message0: 'GetLink %1= link#%2',
    args0: [
      {
        type: 'input_value',
        name: 'RESULT',
        check: 'Value',
      },
      {
        type: 'input_value',
        name: 'VALUE',
        check: 'Value',
      },
    ],
    inputsInline: true,
    previousStatement: null,
    nextStatement: null,
    colour: color.block,
  },
  {
    type: 'LogicControl',
    message0: 'Control set%1of%2%3%4%5%6%7%8%9%10',
    args0: [
      {
        type: 'field_dropdown',
        name: 'TYPE',
        options: [
          ['enabled', 'enabled'],
          ['shoot', 'shoot'],
          ['shootp', 'shootp'],
          ['config', 'config'],
          ['color', 'color'],
        ],
      },
      {
        type: 'input_value',
        name: 'ARG1',
        check: 'Value',
      },
      {
        type: 'field_label_serializable',
        name: 'ARG2S',
      },
      {
        type: 'input_value',
        name: 'ARG2',
        check: 'Value',
      },
      {
        type: 'field_label_serializable',
        name: 'ARG3S',
      },
      {
        type: 'input_value',
        name: 'ARG3',
        check: 'Value',
      },
      {
        type: 'field_label_serializable',
        name: 'ARG4S',
      },
      {
        type: 'input_value',
        name: 'ARG4',
        check: 'Value',
      },
      {
        type: 'field_label_serializable',
        name: 'ARG5S',
      },
      {
        type: 'input_value',
        name: 'ARG5',
        check: 'Value',
      },
    ],
    inputsInline: true,
    previousStatement: null,
    nextStatement: null,
    colour: color.block,
  },
  {
    type: 'LogicRadar',
    message0: 'Radar from%1target%2and%3and%4order%5sort%6output%7',
    args0: [
      {
        type: 'input_value',
        name: 'FROM',
        check: 'Value',
      },
      {
        type: 'field_dropdown',
        name: 'TARGET1',
        options: radar_target,
      },
      {
        type: 'field_dropdown',
        name: 'TARGET2',
        options: radar_target,
      },
      {
        type: 'field_dropdown',
        name: 'TARGET3',
        options: radar_target,
      },
      {
        type: 'input_value',
        name: 'ORDER',
        check: 'Value',
      },
      {
        type: 'field_dropdown',
        name: 'SORT',
        options: radar_sort,
      },
      {
        type: 'input_value',
        name: 'OUTPUT',
        check: 'Value',
      },
    ],
    inputsInline: true,
    previousStatement: null,
    nextStatement: null,
    colour: color.block,
  },
  {
    type: 'SensorOptions',
    message0: 'SensorOpt @%1',
    args0: [
      {
        type: 'field_dropdown',
        name: 'OPTION',
        options: [
          ['totalItems', 'totalItems'],
          ['firstItem', 'firstItem'],
          ['totalLiquids', 'totalLiquids'],
          ['totalPower', 'totalPower'],
          ['itemCapacity', 'itemCapacity'],
          ['liquidCapacity', 'liquidCapacity'],
          ['powerCapacity', 'powerCapacity'],
          ['powerNetStored', 'powerNetStored'],
          ['powerNetCapacity', 'powerNetCapacity'],
          ['powerNetIn', 'powerNetIn'],
          ['powerNetOut', 'powerNetOut'],
          ['ammo', 'ammo'],
          ['ammoCapacity', 'ammoCapacity'],
          ['health', 'health'],
          ['maxHealth', 'maxHealth'],
          ['heat', 'heat'],
          ['shield', 'shield'],
          ['efficiency', 'efficiency'],
          ['progress', 'progress'],
          ['timescale', 'timescale'],
          ['rotation', 'rotation'],
          ['x', 'x'],
          ['y', 'y'],
          ['shootX', 'shootX'],
          ['shootY', 'shootY'],
          ['size', 'size'],
          ['dead', 'dead'],
          ['range', 'range'],
          ['shooting', 'shooting'],
          ['boosting', 'boosting'],
          ['mineX', 'mineX'],
          ['mineY', 'mineY'],
          ['mining', 'mining'],
          ['speed', 'speed'],
          ['team', 'team'],
          ['type', 'type'],
          ['flag', 'flag'],
          ['controlled', 'controlled'],
          ['controller', 'controller'],
          ['name', 'name'],
          ['payloadCount', 'payloadCount'],
          ['payloadType', 'payloadType'],
          ['id', 'id'],
          ['enabled', 'enabled'],
          ['config', 'config'],
          ['color', 'color'],
        ],
      },
    ],
    output: ['Var', 'Value'],
    colour: color.var,
  },
  {
    type: 'LogicSensor',
    message0: 'Sensor%1=%2in%3',
    args0: [
      {
        type: 'input_value',
        name: 'RESULT',
        check: 'Value',
      },
      {
        type: 'input_value',
        name: 'OPTION',
        check: 'Value',
      },
      {
        type: 'input_value',
        name: 'TARGET',
        check: 'Value',
      },
    ],
    inputsInline: true,
    previousStatement: null,
    nextStatement: null,
    colour: color.block,
  },
  {
    type: 'LogicSet',
    message0: 'Set%1=%2',
    args0: [
      {
        type: 'input_value',
        name: 'RESULT',
        check: 'Value',
      },
      {
        type: 'input_value',
        name: 'TARGET',
        check: 'Value',
      },
    ],
    inputsInline: true,
    previousStatement: null,
    nextStatement: null,
    colour: color.operation,
  },
  {
    type: 'LogicOp',
    message0: 'Op%1=%2%3%4',
    args0: [
      {
        type: 'input_value',
        name: 'RESULT',
        check: 'Value',
      },
      {
        type: 'field_dropdown',
        name: 'OPER',
        options: [
          ['+', 'add'],
          ['-', 'sub'],
          ['*', 'mul'],
          ['/', 'div'],
          ['//', 'idiv'],
          ['%', 'mod'],
          ['**', 'pow'],
          ['==', 'equal'],
          ['!=', 'notEqual'],
          ['land', 'land'],
          ['<', 'lessThan'],
          ['<=', 'lessThanEq'],
          ['>', 'greaterThan'],
          ['>=', 'greaterThanEq'],
          ['===', 'strictEqual'],
          ['<<', 'shl'],
          ['>>', 'shr'],
          ['|', 'or'],
          ['&', 'and'],
          ['^', 'xor'],
          ['~', 'not'],
          ['max', 'max'],
          ['min', 'min'],
          ['angle', 'angle'],
          ['angleDiff', 'angleDiff'],
          ['len', 'len'],
          ['noise', 'noise'],
          ['abs', 'abs'],
          ['log', 'log'],
          ['log10', 'log10'],
          ['floor', 'floor'],
          ['ceil', 'ceil'],
          ['sqrt', 'sqrt'],
          ['rand', 'rand'],
          ['sin', 'sin'],
          ['cos', 'cos'],
          ['tan', 'tan'],
          ['asin', 'asin'],
          ['acos', 'acos'],
          ['atan', 'atan'],
        ],
      },
      {
        type: 'input_value',
        name: 'ARG1',
        check: 'Value',
      },
      {
        type: 'input_value',
        name: 'ARG2',
        check: 'Value',
      },
    ],
    inputsInline: true,
    previousStatement: null,
    nextStatement: null,
    colour: color.operation,
  },
  {
    type: 'LogicLookup',
    message0: 'Lookup%1= lookup%2#%3',
    args0: [
      {
        type: 'input_value',
        name: 'RESULT',
        check: 'Value',
      },
      {
        type: 'field_dropdown',
        name: 'TYPE',
        options: [
          ['block', 'block'],
          ['unit', 'unit'],
          ['item', 'item'],
          ['liquid', 'liquid'],
        ],
      },
      {
        type: 'input_value',
        name: 'ID',
        check: 'Value',
      },
    ],
    inputsInline: true,
    previousStatement: null,
    nextStatement: null,
    colour: color.operation,
  },
  {
    type: 'LogicPackColor',
    message0: 'PackColor %1= pack%2%3%4%5',
    args0: [
      {
        type: 'input_value',
        name: 'RESULT',
        check: 'Value',
      },
      {
        type: 'input_value',
        name: 'R',
        check: 'Value',
      },
      {
        type: 'input_value',
        name: 'G',
        check: 'Value',
      },
      {
        type: 'input_value',
        name: 'B',
        check: 'Value',
      },
      {
        type: 'input_value',
        name: 'A',
        check: 'Value',
      },
    ],
    inputsInline: true,
    previousStatement: null,
    nextStatement: null,
    colour: color.operation,
  },
  {
    type: 'LogicWait',
    message0: 'Wait %1',
    args0: [
      {
        type: 'input_value',
        name: 'TIME',
        check: 'Value',
      },
    ],
    inputsInline: true,
    previousStatement: null,
    nextStatement: null,
    colour: color.control,
  },
  {
    type: 'LogicStop',
    message0: 'Stop',
    args0: [],
    inputsInline: true,
    previousStatement: null,
    nextStatement: null,
    colour: color.control,
  },
  {
    type: 'LogicEnd',
    message0: 'End',
    args0: [],
    inputsInline: true,
    previousStatement: null,
    nextStatement: null,
    colour: color.control,
  },
  {
    type: 'Label',
    message0: 'Label :%1',
    args0: [
      {
        type: 'input_value',
        name: 'LABEL',
        check: 'Var',
      }
    ],
    inputsInline: true,
    previousStatement: null,
    nextStatement: null,
    colour: color.bang,
  },
  {
    type: 'CmpNot',
    message0: 'CmpNot%1',
    args0: [
      {
        type: 'input_value',
        name: 'VALUE',
        check: 'Value',
      },
    ],
    output: 'Value',
    colour: color.var,
  },
  {
    type: 'Cmper',
    message0: 'Cmper%1%2%3',
    args0: [
      {
        type: 'input_value',
        name: 'ARG1',
        check: 'Value',
      },
      {
        type: 'field_dropdown',
        name: 'CMPER',
        options: [
          ['==', '=='],
          ['!=', '!='],
          ['<', '<'],
          ['<=', '<='],
          ['>', '>'],
          ['>=', '>='],
          ['===', '==='],
          ['||', '||'],
          ['&&', '&&'],
        ],
      },
      {
        type: 'input_value',
        name: 'ARG2',
        check: 'Value',
      },
    ],
    inputsInline: true,
    output: 'Value',
    colour: color.var,
  },
  {
    type: 'CmpAlways',
    message0: 'CmpAlways',
    output: 'Value',
    colour: color.var,
  },
  {
    type: 'ItemVar',
    message0: 'Item @%1',
    args0: [
      {
        type: 'field_dropdown',
        name: 'ITEM',
        options: [
          ['copper', 'copper'],
          ['lead', 'lead'],
          ['metaglass', 'metaglass'],
          ['graphite', 'graphite'],
          ['sand', 'sand'],
          ['coal', 'coal'],
          ['titanium', 'titanium'],
          ['thorium', 'thorium'],
          ['scrap', 'scrap'],
          ['silicon', 'silicon'],
          ['plastanium', 'plastanium'],
          ['phase-fabric', 'phase-fabric'],
          ['surge-alloy', 'surge-alloy'],
          ['spore-pod', 'spore-pod'],
          ['blast-compound', 'blast-compound'],
          ['pyratite', 'pyratite'],
          ['beryllium', 'beryllium'],
          ['tungsten', 'tungsten'],
          ['oxide', 'oxide'],
          ['carbide', 'carbide'],
          ['fissile-matter', 'fissile-matter'],
          ['dormant-cyst', 'dormant-cyst'],
        ],
      },
    ],
    inputsInline: true,
    output: ['Var', 'Value'],
    colour: color.var,
  },
  {
    type: 'UnitVar',
    message0: 'Unit @%1',
    args0: [
      {
        type: 'field_dropdown',
        name: 'UNIT',
        options: [
          ['dagger', 'dagger'],
          ['mace', 'mace'],
          ['fortress', 'fortress'],
          ['scepter', 'scepter'],
          ['reign', 'reign'],
          ['nova', 'nova'],
          ['pulsar', 'pulsar'],
          ['quasar', 'quasar'],
          ['vela', 'vela'],
          ['corvus', 'corvus'],
          ['crawler', 'crawler'],
          ['atrax', 'atrax'],
          ['spiroct', 'spiroct'],
          ['arkyid', 'arkyid'],
          ['toxopid', 'toxopid'],
          ['flare', 'flare'],
          ['horizon', 'horizon'],
          ['zenith', 'zenith'],
          ['antumbra', 'antumbra'],
          ['eclipse', 'eclipse'],
          ['mono', 'mono'],
          ['poly', 'poly'],
          ['mega', 'mega'],
          ['quad', 'quad'],
          ['oct', 'oct'],
          ['risso', 'risso'],
          ['minke', 'minke'],
          ['bryde', 'bryde'],
          ['sei', 'sei'],
          ['omura', 'omura'],
          ['retusa', 'retusa'],
          ['oxynoe', 'oxynoe'],
          ['cyerce', 'cyerce'],
          ['aegires', 'aegires'],
          ['navanax', 'navanax'],
          ['alpha', 'alpha'],
          ['beta', 'beta'],
          ['gamma', 'gamma'],
          ['stell', 'stell'],
          ['locus', 'locus'],
          ['precept', 'precept'],
          ['vanquish', 'vanquish'],
          ['conquer', 'conquer'],
          ['merui', 'merui'],
          ['cleroi', 'cleroi'],
          ['anthicus', 'anthicus'],
          ['anthicus-missile', 'anthicus-missile'],
          ['tecta', 'tecta'],
          ['collaris', 'collaris'],
          ['elude', 'elude'],
          ['avert', 'avert'],
          ['obviate', 'obviate'],
          ['quell', 'quell'],
          ['quell-missile', 'quell-missile'],
          ['disrupt', 'disrupt'],
          ['disrupt-missile', 'disrupt-missile'],
          ['renale', 'renale'],
          ['latum', 'latum'],
          ['evoke', 'evoke'],
          ['incite', 'incite'],
          ['emanate', 'emanate'],
          ['block', 'block'],
          ['manifold', 'manifold'],
          ['assembly-drone', 'assembly-drone'],
        ],
      },
    ],
    inputsInline: true,
    output: ['Var', 'Value'],
    colour: color.var,
  },
  {
    type: 'BlockVar',
    message0: 'Block @%1',
    args0: [
      {
        type: 'field_dropdown',
        name: 'BLOCK',
        options: [
          ['additive-reconstructor', 'additive-reconstructor'],
          ['afflict', 'afflict'],
          ['air', 'air'],
          ['air-factory', 'air-factory'],
          ['arc', 'arc'],
          ['arkycite-floor', 'arkycite-floor'],
          ['arkyic-boulder', 'arkyic-boulder'],
          ['arkyic-stone', 'arkyic-stone'],
          ['arkyic-vent', 'arkyic-vent'],
          ['arkyic-wall', 'arkyic-wall'],
          ['armored-conveyor', 'armored-conveyor'],
          ['armored-duct', 'armored-duct'],
          ['atmospheric-concentrator', 'atmospheric-concentrator'],
          ['barrier-projector', 'barrier-projector'],
          ['basalt', 'basalt'],
          ['basalt-boulder', 'basalt-boulder'],
          ['basic-assembler-module', 'basic-assembler-module'],
          ['battery', 'battery'],
          ['battery-large', 'battery-large'],
          ['beam-link', 'beam-link'],
          ['beam-node', 'beam-node'],
          ['beam-tower', 'beam-tower'],
          ['beryllic-boulder', 'beryllic-boulder'],
          ['beryllic-stone', 'beryllic-stone'],
          ['beryllic-stone-wall', 'beryllic-stone-wall'],
          ['beryllium-wall', 'beryllium-wall'],
          ['beryllium-wall-large', 'beryllium-wall-large'],
          ['blast-door', 'blast-door'],
          ['blast-drill', 'blast-drill'],
          ['blast-mixer', 'blast-mixer'],
          ['bluemat', 'bluemat'],
          ['boulder', 'boulder'],
          ['breach', 'breach'],
          ['bridge-conduit', 'bridge-conduit'],
          ['bridge-conveyor', 'bridge-conveyor'],
          ['build-tower', 'build-tower'],
          ['canvas', 'canvas'],
          ['carbide-crucible', 'carbide-crucible'],
          ['carbide-wall', 'carbide-wall'],
          ['carbide-wall-large', 'carbide-wall-large'],
          ['carbon-boulder', 'carbon-boulder'],
          ['carbon-stone', 'carbon-stone'],
          ['carbon-vent', 'carbon-vent'],
          ['carbon-wall', 'carbon-wall'],
          ['char', 'char'],
          ['chemical-combustion-chamber', 'chemical-combustion-chamber'],
          ['cliff', 'cliff'],
          ['cliff-crusher', 'cliff-crusher'],
          ['coal-centrifuge', 'coal-centrifuge'],
          ['combustion-generator', 'combustion-generator'],
          ['conduit', 'conduit'],
          ['constructor', 'constructor'],
          ['container', 'container'],
          ['conveyor', 'conveyor'],
          ['copper-wall', 'copper-wall'],
          ['copper-wall-large', 'copper-wall-large'],
          ['core-acropolis', 'core-acropolis'],
          ['core-bastion', 'core-bastion'],
          ['core-citadel', 'core-citadel'],
          ['core-foundation', 'core-foundation'],
          ['core-nucleus', 'core-nucleus'],
          ['core-shard', 'core-shard'],
          ['core-zone', 'core-zone'],
          ['crater-stone', 'crater-stone'],
          ['cryofluid-mixer', 'cryofluid-mixer'],
          ['crystal-blocks', 'crystal-blocks'],
          ['crystal-cluster', 'crystal-cluster'],
          ['crystal-floor', 'crystal-floor'],
          ['crystal-orbs', 'crystal-orbs'],
          ['crystalline-boulder', 'crystalline-boulder'],
          ['crystalline-stone', 'crystalline-stone'],
          ['crystalline-stone-wall', 'crystalline-stone-wall'],
          ['crystalline-vent', 'crystalline-vent'],
          ['cultivator', 'cultivator'],
          ['cyanogen-synthesizer', 'cyanogen-synthesizer'],
          ['cyclone', 'cyclone'],
          ['dacite', 'dacite'],
          ['dacite-boulder', 'dacite-boulder'],
          ['dacite-wall', 'dacite-wall'],
          ['dark-metal', 'dark-metal'],
          ['darksand', 'darksand'],
          ['darksand-tainted-water', 'darksand-tainted-water'],
          ['darksand-water', 'darksand-water'],
          ['deconstructor', 'deconstructor'],
          ['deep-tainted-water', 'deep-tainted-water'],
          ['deep-water', 'deep-water'],
          ['dense-red-stone', 'dense-red-stone'],
          ['differential-generator', 'differential-generator'],
          ['diffuse', 'diffuse'],
          ['diode', 'diode'],
          ['dirt', 'dirt'],
          ['dirt-wall', 'dirt-wall'],
          ['disassembler', 'disassembler'],
          ['disperse', 'disperse'],
          ['distributor', 'distributor'],
          ['door', 'door'],
          ['door-large', 'door-large'],
          ['duct', 'duct'],
          ['duct-bridge', 'duct-bridge'],
          ['duct-router', 'duct-router'],
          ['duct-unloader', 'duct-unloader'],
          ['dune-wall', 'dune-wall'],
          ['duo', 'duo'],
          ['eb7abe', 'eb7abe'],
          ['electric-heater', 'electric-heater'],
          ['electrolyzer', 'electrolyzer'],
          ['empty', 'empty'],
          ['eruption-drill', 'eruption-drill'],
          ['exponential-reconstructor', 'exponential-reconstructor'],
          ['ferric-boulder', 'ferric-boulder'],
          ['ferric-craters', 'ferric-craters'],
          ['ferric-stone', 'ferric-stone'],
          ['ferric-stone-wall', 'ferric-stone-wall'],
          ['flux-reactor', 'flux-reactor'],
          ['force-projector', 'force-projector'],
          ['foreshadow', 'foreshadow'],
          ['fuse', 'fuse'],
          ['graphite-press', 'graphite-press'],
          ['graphitic-wall', 'graphitic-wall'],
          ['grass', 'grass'],
          ['ground-factory', 'ground-factory'],
          ['hail', 'hail'],
          ['heat-reactor', 'heat-reactor'],
          ['heat-redirector', 'heat-redirector'],
          ['heat-router', 'heat-router'],
          ['heat-source', 'heat-source'],
          ['hotrock', 'hotrock'],
          ['hyper-processor', 'hyper-processor'],
          ['ice', 'ice'],
          ['ice-snow', 'ice-snow'],
          ['ice-wall', 'ice-wall'],
          ['illuminator', 'illuminator'],
          ['impact-drill', 'impact-drill'],
          ['impact-reactor', 'impact-reactor'],
          ['impulse-pump', 'impulse-pump'],
          ['incinerator', 'incinerator'],
          ['interplanetary-accelerator', 'interplanetary-accelerator'],
          ['inverted-sorter', 'inverted-sorter'],
          ['item-source', 'item-source'],
          ['item-void', 'item-void'],
          ['junction', 'junction'],
          ['kiln', 'kiln'],
          ['lancer', 'lancer'],
          ['large-constructor', 'large-constructor'],
          ['large-logic-display', 'large-logic-display'],
          ['large-payload-mass-driver', 'large-payload-mass-driver'],
          ['large-plasma-bore', 'large-plasma-bore'],
          ['large-shield-projector', 'large-shield-projector'],
          ['laser-drill', 'laser-drill'],
          ['launch-pad', 'launch-pad'],
          ['liquid-container', 'liquid-container'],
          ['liquid-junction', 'liquid-junction'],
          ['liquid-router', 'liquid-router'],
          ['liquid-source', 'liquid-source'],
          ['liquid-tank', 'liquid-tank'],
          ['liquid-void', 'liquid-void'],
          ['logic-display', 'logic-display'],
          ['logic-processor', 'logic-processor'],
          ['lustre', 'lustre'],
          ['magmarock', 'magmarock'],
          ['malign', 'malign'],
          ['mass-driver', 'mass-driver'],
          ['mech-assembler', 'mech-assembler'],
          ['mech-fabricator', 'mech-fabricator'],
          ['mech-refabricator', 'mech-refabricator'],
          ['mechanical-drill', 'mechanical-drill'],
          ['mechanical-pump', 'mechanical-pump'],
          ['meltdown', 'meltdown'],
          ['melter', 'melter'],
          ['memory-bank', 'memory-bank'],
          ['memory-cell', 'memory-cell'],
          ['mend-projector', 'mend-projector'],
          ['mender', 'mender'],
          ['message', 'message'],
          ['micro-processor', 'micro-processor'],
          ['molten-slag', 'molten-slag'],
          ['moss', 'moss'],
          ['mud', 'mud'],
          ['multi-press', 'multi-press'],
          ['multiplicative-reconstructor', 'multiplicative-reconstructor'],
          ['naval-factory', 'naval-factory'],
          ['neoplasia-reactor', 'neoplasia-reactor'],
          ['oil-extractor', 'oil-extractor'],
          ['overdrive-dome', 'overdrive-dome'],
          ['overdrive-projector', 'overdrive-projector'],
          ['overflow-duct', 'overflow-duct'],
          ['overflow-gate', 'overflow-gate'],
          ['oxidation-chamber', 'oxidation-chamber'],
          ['parallax', 'parallax'],
          ['payload-conveyor', 'payload-conveyor'],
          ['payload-loader', 'payload-loader'],
          ['payload-mass-driver', 'payload-mass-driver'],
          ['payload-router', 'payload-router'],
          ['payload-source', 'payload-source'],
          ['payload-unloader', 'payload-unloader'],
          ['payload-void', 'payload-void'],
          ['pebbles', 'pebbles'],
          ['phase-conduit', 'phase-conduit'],
          ['phase-conveyor', 'phase-conveyor'],
          ['phase-heater', 'phase-heater'],
          ['phase-synthesizer', 'phase-synthesizer'],
          ['phase-wall', 'phase-wall'],
          ['phase-wall-large', 'phase-wall-large'],
          ['phase-weaver', 'phase-weaver'],
          ['pine', 'pine'],
          ['plasma-bore', 'plasma-bore'],
          ['plastanium-compressor', 'plastanium-compressor'],
          ['plastanium-conveyor', 'plastanium-conveyor'],
          ['plastanium-wall', 'plastanium-wall'],
          ['plastanium-wall-large', 'plastanium-wall-large'],
          ['plated-conduit', 'plated-conduit'],
          ['pneumatic-drill', 'pneumatic-drill'],
          ['pooled-cryofluid', 'pooled-cryofluid'],
          ['power-node', 'power-node'],
          ['power-node-large', 'power-node-large'],
          ['power-source', 'power-source'],
          ['power-void', 'power-void'],
          ['prime-refabricator', 'prime-refabricator'],
          ['pulse-conduit', 'pulse-conduit'],
          ['pulverizer', 'pulverizer'],
          ['pur-bush', 'pur-bush'],
          ['pyratite-mixer', 'pyratite-mixer'],
          ['pyrolysis-generator', 'pyrolysis-generator'],
          ['radar', 'radar'],
          ['red-diamond-wall', 'red-diamond-wall'],
          ['red-ice', 'red-ice'],
          ['red-ice-boulder', 'red-ice-boulder'],
          ['red-ice-wall', 'red-ice-wall'],
          ['red-stone', 'red-stone'],
          ['red-stone-boulder', 'red-stone-boulder'],
          ['red-stone-vent', 'red-stone-vent'],
          ['red-stone-wall', 'red-stone-wall'],
          ['redmat', 'redmat'],
          ['redweed', 'redweed'],
          ['regen-projector', 'regen-projector'],
          ['regolith', 'regolith'],
          ['regolith-wall', 'regolith-wall'],
          ['reinforced-', 'reinforced-'],
          ['reinforced-', 'reinforced-'],
          ['reinforced-', 'reinforced-'],
          ['reinforced-', 'reinforced-'],
          ['reinforced-', 'reinforced-'],
          ['reinforced-', 'reinforced-'],
          ['reinforced-', 'reinforced-'],
          ['reinforced-', 'reinforced-'],
          ['reinforced-', 'reinforced-'],
          ['reinforced-', 'reinforced-'],
          ['reinforced-bridge-conduit', 'reinforced-bridge-conduit'],
          ['reinforced-conduit', 'reinforced-conduit'],
          ['reinforced-container', 'reinforced-container'],
          ['reinforced-liquid-container', 'reinforced-liquid-container'],
          ['reinforced-liquid-junction', 'reinforced-liquid-junction'],
          ['reinforced-liquid-router', 'reinforced-liquid-router'],
          ['reinforced-liquid-tank', 'reinforced-liquid-tank'],
          ['reinforced-message', 'reinforced-message'],
          ['reinforced-payload-conveyor', 'reinforced-payload-conveyor'],
          ['reinforced-payload-router', 'reinforced-payload-router'],
          ['reinforced-pump', 'reinforced-pump'],
          ['reinforced-surge-wall', 'reinforced-surge-wall'],
          ['reinforced-surge-wall-large', 'reinforced-surge-wall-large'],
          ['reinforced-vault', 'reinforced-vault'],
          ['repair-point', 'repair-point'],
          ['repair-turret', 'repair-turret'],
          ['rhyolite', 'rhyolite'],
          ['rhyolite-boulder', 'rhyolite-boulder'],
          ['rhyolite-crater', 'rhyolite-crater'],
          ['rhyolite-vent', 'rhyolite-vent'],
          ['rhyolite-wall', 'rhyolite-wall'],
          ['ripple', 'ripple'],
          ['rotary-pump', 'rotary-pump'],
          ['rough-rhyolite', 'rough-rhyolite'],
          ['router', 'router'],
          ['rtg-generator', 'rtg-generator'],
          ['salt', 'salt'],
          ['salt-wall', 'salt-wall'],
          ['salvo', 'salvo'],
          ['sand-boulder', 'sand-boulder'],
          ['sand-floor', 'sand-floor'],
          ['sand-wall', 'sand-wall'],
          ['sand-water', 'sand-water'],
          ['scathe', 'scathe'],
          ['scathe-missile', 'scathe-missile'],
          ['scatter', 'scatter'],
          ['scorch', 'scorch'],
          ['scrap-wall', 'scrap-wall'],
          ['scrap-wall-gigantic', 'scrap-wall-gigantic'],
          ['scrap-wall-huge', 'scrap-wall-huge'],
          ['scrap-wall-large', 'scrap-wall-large'],
          ['segment', 'segment'],
          ['separator', 'separator'],
          ['shale', 'shale'],
          ['shale-boulder', 'shale-boulder'],
          ['shale-wall', 'shale-wall'],
          ['shallow-water', 'shallow-water'],
          ['shield-projector', 'shield-projector'],
          ['shielded-wall', 'shielded-wall'],
          ['ship-assembler', 'ship-assembler'],
          ['ship-fabricator', 'ship-fabricator'],
          ['ship-refabricator', 'ship-refabricator'],
          ['shock-mine', 'shock-mine'],
          ['shockwave-tower', 'shockwave-tower'],
          ['shrubs', 'shrubs'],
          ['silicon-arc-furnace', 'silicon-arc-furnace'],
          ['silicon-crucible', 'silicon-crucible'],
          ['silicon-smelter', 'silicon-smelter'],
          ['slag-centrifuge', 'slag-centrifuge'],
          ['slag-heater', 'slag-heater'],
          ['slag-incinerator', 'slag-incinerator'],
          ['small-deconstructor', 'small-deconstructor'],
          ['smite', 'smite'],
          ['snow', 'snow'],
          ['snow-boulder', 'snow-boulder'],
          ['snow-pine', 'snow-pine'],
          ['snow-wall', 'snow-wall'],
          ['solar-panel', 'solar-panel'],
          ['solar-panel-large', 'solar-panel-large'],
          ['sorter', 'sorter'],
          ['space', 'space'],
          ['spawn', 'spawn'],
          ['spectre', 'spectre'],
          ['spore-cluster', 'spore-cluster'],
          ['spore-moss', 'spore-moss'],
          ['spore-pine', 'spore-pine'],
          ['spore-press', 'spore-press'],
          ['spore-wall', 'spore-wall'],
          ['steam-generator', 'steam-generator'],
          ['stone', 'stone'],
          ['stone-wall', 'stone-wall'],
          ['sublimate', 'sublimate'],
          ['surge-conveyor', 'surge-conveyor'],
          ['surge-crucible', 'surge-crucible'],
          ['surge-router', 'surge-router'],
          ['surge-smelter', 'surge-smelter'],
          ['surge-tower', 'surge-tower'],
          ['surge-wall', 'surge-wall'],
          ['surge-wall-large', 'surge-wall-large'],
          ['swarmer', 'swarmer'],
          ['switch', 'switch'],
          ['tainted-water', 'tainted-water'],
          ['tank-assembler', 'tank-assembler'],
          ['tank-fabricator', 'tank-fabricator'],
          ['tank-refabricator', 'tank-refabricator'],
          ['tar', 'tar'],
          ['tendrils', 'tendrils'],
          ['tetrative-reconstructor', 'tetrative-reconstructor'],
          ['thermal-generator', 'thermal-generator'],
          ['thorium-reactor', 'thorium-reactor'],
          ['thorium-wall', 'thorium-wall'],
          ['thorium-wall-large', 'thorium-wall-large'],
          ['thruster', 'thruster'],
          ['titan', 'titan'],
          ['titanium-conveyor', 'titanium-conveyor'],
          ['titanium-wall', 'titanium-wall'],
          ['titanium-wall-large', 'titanium-wall-large'],
          ['tsunami', 'tsunami'],
          ['tungsten-wall', 'tungsten-wall'],
          ['tungsten-wall-large', 'tungsten-wall-large'],
          ['turbine-condenser', 'turbine-condenser'],
          ['underflow-duct', 'underflow-duct'],
          ['underflow-gate', 'underflow-gate'],
          ['unit-cargo-loader', 'unit-cargo-loader'],
          ['unit-cargo-unload-point', 'unit-cargo-unload-point'],
          ['unit-repair-tower', 'unit-repair-tower'],
          ['unloader', 'unloader'],
          ['vault', 'vault'],
          ['vent-condenser', 'vent-condenser'],
          ['vibrant-crystal-cluster', 'vibrant-crystal-cluster'],
          ['water-extractor', 'water-extractor'],
          ['wave', 'wave'],
          ['white-tree', 'white-tree'],
          ['white-tree-dead', 'white-tree-dead'],
          ['world-cell', 'world-cell'],
          ['world-message', 'world-message'],
          ['world-processor', 'world-processor'],
          ['yellow-stone', 'yellow-stone'],
          ['yellow-stone-boulder', 'yellow-stone-boulder'],
          ['yellow-stone-plates', 'yellow-stone-plates'],
          ['yellow-stone-vent', 'yellow-stone-vent'],
          ['yellow-stone-wall', 'yellow-stone-wall'],
          ['yellowcoral', 'yellowcoral'],
        ],
      },
    ],
    inputsInline: true,
    output: ['Var', 'Value'],
    colour: color.var,
  },
  {
    type: 'LiquidVar',
    message0: 'Liquid @%1',
    args0: [
      {
        type: 'field_dropdown',
        name: 'LIQUID',
        options: [
          ['water', 'water'],
          ['slag', 'slag'],
          ['oil', 'oil'],
          ['cryofluid', 'cryofluid'],
          ['neoplasm', 'neoplasm'],
          ['arkycite', 'arkycite'],
          ['gallium', 'gallium'],
          ['ozone', 'ozone'],
          ['hydrogen', 'hydrogen'],
          ['nitrogen', 'nitrogen'],
          ['cyanogen', 'cyanogen'],
        ],
      },
    ],
    inputsInline: true,
    output: ['Var', 'Value'],
    colour: color.var,
  },
  {
    type: 'LogicUnitBind',
    message0: 'UnitBind%1',
    args0: [
      {
        type: 'input_value',
        name: 'VALUE',
        check: 'Value',
      },
    ],
    inputsInline: true,
    previousStatement: null,
    nextStatement: null,
    colour: color.unit,
  },
  {
    type: 'LogicUnitControl',
    message0: 'UnitControl%1%2%3%4%5%6%7%8%9%10%11',
    args0: [
      {
        type: 'field_dropdown',
        name: 'TYPE',
        options: [
          ['idle', 'idle'],
          ['stop', 'stop'],
          ['move', 'move'],
          ['approach', 'approach'],
          ['pathfind', 'pathfind'],
          ['autoPathfind', 'autoPathfind'],
          ['boost', 'boost'],
          ['target', 'target'],
          ['targetp', 'targetp'],
          ['itemDrop', 'itemDrop'],
          ['itemTake', 'itemTake'],
          ['payDrop', 'payDrop'],
          ['payTake', 'payTake'],
          ['payEnter', 'payEnter'],
          ['mine', 'mine'],
          ['flag', 'flag'],
          ['build', 'build'],
          ['getBlock', 'getBlock'],
          ['within', 'within'],
          ['unbind', 'unbind'],
        ],
      },
      {
        type: 'field_label_serializable',
        name: 'ARG1S',
      },
      {
        type: 'input_value',
        name: 'ARG1',
        check: 'Value',
      },
      {
        type: 'field_label_serializable',
        name: 'ARG2S',
      },
      {
        type: 'input_value',
        name: 'ARG2',
        check: 'Value',
      },
      {
        type: 'field_label_serializable',
        name: 'ARG3S',
      },
      {
        type: 'input_value',
        name: 'ARG3',
        check: 'Value',
      },
      {
        type: 'field_label_serializable',
        name: 'ARG4S',
      },
      {
        type: 'input_value',
        name: 'ARG4',
        check: 'Value',
      },
      {
        type: 'field_label_serializable',
        name: 'ARG5S',
      },
      {
        type: 'input_value',
        name: 'ARG5',
        check: 'Value',
      },
    ],
    inputsInline: true,
    previousStatement: null,
    nextStatement: null,
    colour: color.unit,
  },
  {
    type: 'LogicUnitRadar',
    message0: 'UnitRadar target%1and%2and%3order%4sort%5output%6',
    args0: [
      {
        type: 'field_dropdown',
        name: 'TARGET1',
        options: radar_target,
      },
      {
        type: 'field_dropdown',
        name: 'TARGET2',
        options: radar_target,
      },
      {
        type: 'field_dropdown',
        name: 'TARGET3',
        options: radar_target,
      },
      {
        type: 'input_value',
        name: 'ORDER',
        check: 'Value',
      },
      {
        type: 'field_dropdown',
        name: 'SORT',
        options: radar_sort,
      },
      {
        type: 'input_value',
        name: 'OUTPUT',
        check: 'Value',
      },
    ],
    inputsInline: true,
    previousStatement: null,
    nextStatement: null,
    colour: color.unit,
  },
  {
    type: 'LogicUnitLocate',
    message0: 'UnitLocate find%1%2%3%4%5%6%7%8%9%10%11%12%13%14%15',
    args0: [
      {
        type: 'field_dropdown',
        name: 'TYPE',
        options: [
          ['building', 'building'],
          ['ore', 'ore'],
          ['spawn', 'spawn'],
          ['damaged', 'damaged'],
        ],
      },
      {
        type: 'field_label_serializable',
        name: 'ARG1S',
      },
      {
        type: 'field_dropdown',
        name: 'ARG1',
        options: [
          ['core', 'core'],
          ['storage', 'storage'],
          ['generator', 'generator'],
          ['turret', 'turret'],
          ['factory', 'factory'],
          ['repair', 'repair'],
          ['rally', 'rally'],
          ['battery', 'battery'],
          ['reactor', 'reactor'],
        ],
      },
      {
        type: 'field_label_serializable',
        name: 'ARG2S',
      },
      {
        type: 'input_value',
        name: 'ARG2',
        check: 'Value',
      },
      {
        type: 'field_label_serializable',
        name: 'ARG3S',
      },
      {
        type: 'input_value',
        name: 'ARG3',
        check: 'Value',
      },
      {
        type: 'field_label_serializable',
        name: 'ARG4S',
      },
      {
        type: 'input_value',
        name: 'ARG4',
        check: 'Value',
      },
      {
        type: 'field_label_serializable',
        name: 'ARG5S',
      },
      {
        type: 'input_value',
        name: 'ARG5',
        check: 'Value',
      },
      {
        type: 'field_label_serializable',
        name: 'ARG6S',
      },
      {
        type: 'input_value',
        name: 'ARG6',
        check: 'Value',
      },
      {
        type: 'field_label_serializable',
        name: 'ARG7S',
      },
      {
        type: 'input_value',
        name: 'ARG7',
        check: 'Value',
      },
    ],
    inputsInline: true,
    previousStatement: null,
    nextStatement: null,
    colour: color.unit,
  },
  {
    type: 'DoWhile',
    message0: 'do {',
    message1: '%1',
    message2: '} while%1',
    args1: [
      {
        type: 'input_statement',
        name: 'LINES',
      },
    ],
    args2: [
      {
        type: 'input_value',
        name: 'VALUE',
        check: 'Value',
      },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: color.bang,
  },
  {
    type: 'Goto',
    message0: 'Goto :%1 %2',
    args0: [
      {
        type: 'input_value',
        name: 'LABEL',
        check: 'Var',
      },
      {
        type: 'input_value',
        name: 'VALUE',
        check: 'Value',
      },
    ],
    inputsInline: true,
    previousStatement: null,
    nextStatement: null,
    colour: color.bang,
  },
  {
    type: 'Source',
    message0: 'Source%1',
    args0: [
      {
        type: 'field_input',
        name: 'SOURCE',
      },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: color.bang,
  },
  {
    type: 'Else',
    message0: 'else',
    message1: '%1',
    args1: [
      {
        type: 'input_statement',
        name: 'LINES',
      },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: color.bang,
  },
  {
    type: 'DExp',
    message0: 'DExp%1%2',
    args0: [
      {
        type: 'input_value',
        name: 'RESULT',
        check: 'Var',
      },
      {
        type: 'input_statement',
        name: 'LINES',
      },
    ],
    output: 'Value',
    colour: color.var,
  },
  {
    type: 'ResultHandle',
    message0: 'ResultHandle $',
    args0: [],
    output: 'Value',
    colour: color.var,
  },
  {
    type: 'Const',
    message0: 'const %1 = %2',
    args0: [
      {
        type: 'input_value',
        name: 'NAME',
        check: 'Var',
      },
      {
        type: 'input_value',
        name: 'VALUE',
        check: 'Value',
      },
    ],
    inputsInline: true,
    previousStatement: null,
    nextStatement: null,
    colour: color.bang,
  },
  {
    type: 'Take',
    message0: 'take %1 = %2',
    args0: [
      {
        type: 'input_value',
        name: 'NAME',
        check: 'Var',
      },
      {
        type: 'input_value',
        name: 'VALUE',
        check: 'Value',
      },
    ],
    inputsInline: true,
    previousStatement: null,
    nextStatement: null,
    colour: color.bang,
  },
  {
    type: 'QuickTake',
    message0: 'QuickTake%1[%2%3%4%5%6%7%8%9%10%11]',
    args0: [
      {
        type: 'input_value',
        name: 'VAR',
        check: 'Var',
      },
      {
        type: 'input_value',
        name: 'ARG0',
        check: 'Value',
      },
      {
        type: 'input_value',
        name: 'ARG1',
        check: 'Value',
      },
      {
        type: 'input_value',
        name: 'ARG2',
        check: 'Value',
      },
      {
        type: 'input_value',
        name: 'ARG3',
        check: 'Value',
      },
      {
        type: 'input_value',
        name: 'ARG4',
        check: 'Value',
      },
      {
        type: 'input_value',
        name: 'ARG5',
        check: 'Value',
      },
      {
        type: 'input_value',
        name: 'ARG6',
        check: 'Value',
      },
      {
        type: 'input_value',
        name: 'ARG7',
        check: 'Value',
      },
      {
        type: 'input_value',
        name: 'ARG8',
        check: 'Value',
      },
      {
        type: 'input_value',
        name: 'ARG9',
        check: 'Value',
      },
    ],
    output: 'Value',
    colour: color.var,
  },
  {
    type: 'SwitchCase',
    message0: 'case %1:',
    args0: [
      {
        type: 'field_input',
        name: 'ID',
        text: '0',
      },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: color.bang,
  },
  {
    type: 'ControlPlus',
    message0: '%1%2',
    args0: [
      {
        type: 'field_dropdown',
        name: 'TYPE',
        options: [
          ['break', 'break'],
          ['continue', 'continue'],
        ],
      },
      {
        type: 'input_value',
        name: 'VALUE',
        check: 'Value',
      },
    ],
    previousStatement: null,
    nextStatement: null,
    colour: color.bang,
  },
  {
    type: 'ControlBlock',
    message0: '%1 %2 {',
    args0: [
      {
        type: 'field_dropdown',
        name: 'BREAK_TYPE',
        options: [
          ['break', 'break'],
          ['break!', 'break!'],
          ['unused', ''],
        ],
      },
      {
        type: 'field_dropdown',
        name: 'CONTINUE_TYPE',
        options: [
          ['continue', 'continue'],
          ['continue!', 'continue!'],
          ['unused', ''],
        ],
      },
    ],
    message1: '%1',
    args1: [
      {
        type: 'input_statement',
        name: 'LINES',
      },
    ],
    message2: '}',
    previousStatement: null,
    nextStatement: null,
    colour: color.bang,
  },
  {
    type: 'InlineBlock',
    message0: 'inline {',
    message1: '%1',
    args1: [
      {
        type: 'input_statement',
        name: 'LINES',
      },
    ],
    message2: '}',
    previousStatement: null,
    nextStatement: null,
    colour: color.bang,
  },
]);
